---
#site setings 
title: Filoscimientos
author: 
 name: Cecilia Iveth Molgado garfias
 email: cezimg@gmail.com
 description: Todo lo que te has preguntado de la Filosofía aqui lo encontraras. 

theme: jekyll-theme-cayman
